# Generated by Django 6.1.2 on 2026-10-08 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='locationview',
            new_name='locview_loc_viewed_idx',
            old_name='locations_l_locatio_3c7284_idx',
        ),
        migrations.AddIndex(
            model_name='locationview',
            index=models.Index(fields=['viewed_at'], name='locview_viewed_idx'),
        ),
    ]
